version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - db_data:/app  # Mount the SQLite database file to persist data
    environment:
      - DB_NAME=/app/db.sqlite3  # Path to the SQLite3 database file inside the container

volumes:
  db_data:
    driver: local  # Use local driver for SQLite database persistence
