version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/app   # Map the local mysite directory to /app in the container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=/db_data/db2.sqlite3  # Path to the SQLite3 database file inside the container
      - DB_USER=
      - DB_PASSWORD=

  db:
    image: nouchka/sqlite:latest
    volumes:
      - ./mysite/   # Map the local directory containing the SQLite3 database file
