# Generated by Django 5.0.6 on 2024-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/veg'),
        ),
    ]
