# Generated by Django 5.0.6 on 2024-10-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_veg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='veg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='veg'),
        ),
        migrations.AddField(
            model_name='veg',
            name='catalogue',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='myapp.cat'),
        ),
    ]
