# Generated by Django 5.0.6 on 2024-10-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cat_alter_veg_img_veg_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veg',
            name='catalogue',
        ),
    ]
